language: node_js
<<<<<<< HEAD
node_js: 
  - "6"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - mongodb-3.2-precise

    packages:
      - g++-4.8
      - mongodb-org-server
=======
node_js:
  - "6"
>>>>>>> a46e343aeceb9a7d24f0167f11a6867036e4c4ff
